# Configuration for .github/workflows/pull_request_label.yml.

"package-args":
  - changed-files:
      - any-glob-to-any-file: 'pkgs/args/**'

"package-characters":
  - changed-files:
      - any-glob-to-any-file: 'pkgs/characters/**'
