# Configuration for .github/workflows/pull_request_label.yaml.

"package:args":
  - changed-files:
      - any-glob-to-any-file: 'pkgs/args/**'

"package:convert":
  - changed-files:
      - any-glob-to-any-file: 'pkgs/convert/**'

"package:crypto":
  - changed-files:
      - any-glob-to-any-file: 'pkgs/crypto/**'

"package:fixnum":
  - changed-files:
      - any-glob-to-any-file: 'pkgs/fixnum/**'
