name: os_detect
version: 1.0.0
description: Platform independent OS detection.
homepage: https://github.com/dart-lang/os_detect
environment:
  sdk: ">=2.8.0 <3.0.0"
dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.15.0
