name: async
version: 1.1.1
author: Dart Team <misc@dartlang.org>
description: Utility functions and classes related to the 'dart:async' library.
homepage: https://www.github.com/dart-lang/async
dev_dependencies:
  unittest: ">=0.10.0 <0.12.0"
environment:
  sdk: ">=1.9.0 <2.0.0"
