name: async
version: 1.2.0
author: Dart Team <misc@dartlang.org>
description: Utility functions and classes related to the 'dart:async' library.
homepage: https://www.github.com/dart-lang/async
dev_dependencies:
  test: "^0.12.0"
  stack_trace: "^1.0.0"
environment:
  sdk: ">=1.9.0-dev.8.4 <2.0.0"
