name: async
version: 1.9.1-dev
author: Dart Team <misc@dartlang.org>
description: Utility functions and classes related to the 'dart:async' library.
homepage: https://www.github.com/dart-lang/async
dev_dependencies:
  fake_async: "^0.1.2"
  stack_trace: "^1.0.0"
  test: "^0.12.0"
environment:
  sdk: ">=1.12.0 <2.0.0"
