name: convert
version: 0.0.1
description: Utilities for converting between data representations.
author: Dart Team <misc@dartlang.org>
homepage: https://github.com/dart-lang/convert

environment:
  sdk: '>=1.8.0 <2.0.0'

dev_dependencies:
  test: '^1.12.0'
